### ISSUE TITLE
Fixing spelling errors in text: [netstats -na | grep 5070]

### ISSUE THREAD

**Issue by Maxwell2020152049** [Omid-Mohajerani/freeswitch#1]
`netstats -na | grep 5070` should be `netstat -na | grep 5070`

**Comment by Maxwell2020152049** [comment]
in here: [Learn FreeSWITCH part 6 SIP Profile, Directory and Dialplan](https://github.com/Omid-Mohajerani/freeswitch/wiki/Learn-FreeSWITCH-part-6---SIP-Profile,-Directory-and-Dialplan)

**Comment by Omid-Mohajerani** [comment]
@Maxwell2020152049 thank you. fixed
